version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5555:5555'
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - .:/app
      - /app/node_modules/
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: quizziky
    ports:
      - '3307:3306'
    networks:
      - mynetwork
    volumes:
      - ./db_data:/var/lib/mysql
networks:
  mynetwork:
